### PR TITLE
Fix folder autocreation

### PR DESCRIPTION
**Pull request by fl42**
See #15

### CODE REVIEW

**Comment by jgosmann** [comment]
Thank you for the contribution! It might take me after Christmas to try this out. Assuming that this fixes the issue without breaking things, it would be nice to have a regression test. Though, I am not sure if that's easily possible if the previous implementation worked with Greenmail (the dev mail server against which the tests run).

**Comment by fl42** [comment]
The issue looks related to the IMAP implementation of Office365, then I'm not sure how to test it with Greenmail
I'll have a look to add tests

**Comment by fl42** [comment]
I added a test for `create_if_not_exists` method
Is it that you expected?

**Comment by jgosmann** [comment]
I made some minor changes, see fl42/dmarc-metrics-exporter#1. Please merge them if they look good to you and I will take care to merge them back to this repository and then doing a bugfix release.

**Pull request merged**
